accum_grad: 1
adam_betas: (0.9, 0.999)
adam_eps: 1.0e-08
add_eos: false
cat_sent: false
d_inner_hid: 2048
d_k: 64
d_model: 512
d_v: 64
data_workers: 8
descend_steps: 3000000
dropout: 0.3
eval_max_tok: 400000
fp16: true
fp16_opt_level: O3
gpus: -1
load_checkpoint: null
lr: 0.0001
lr_schedule: fixed
max_epochs: 3000
max_len: 205
max_steps: 5000000
max_tok: 15000
model_name: new_pure_ckpt
model_type: blm
multigpu: true
n_head: 8
n_layers: 6
n_mc: 1
root_dir: icsd_strit_web/blm
save_top_k: 20
seed: 1111
share_emb_prj_weight: true
train: blankfill_dataset/icsd_strict_web/icsd_strict_train.txt
val_check_interval: 0
valid: blankfill_dataset/icsd_strict_web/icsd_strict_valid.txt
vocab_size: 99
warmup_steps: 4000
weight_decay: 1.0e-05
